//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSenAdmin.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationSurname { get; set; }
        public string ApplicationIdentityNumber { get; set; }
        public string ApplicationFatherName { get; set; }
        public string ApplicationMotherName { get; set; }
        public string ApplicationBornPlace { get; set; }
        public Nullable<System.DateTime> ApplicationBornDate { get; set; }
        public Nullable<int> ApplicationGenderID { get; set; }
        public Nullable<int> ApplicationEducationID { get; set; }
        public Nullable<int> ApplicationOrganisationID { get; set; }
        public string ApplicationWorkPlaceName { get; set; }
        public Nullable<int> ApplicationProvinceID { get; set; }
        public Nullable<int> ApplicationDistrictID { get; set; }
        public Nullable<int> ApplicationStaffID { get; set; }
        public Nullable<int> ApplicationBloodTypeID { get; set; }
        public string ApplicationPhoneNumber { get; set; }
        public string ApplicationEmail { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> ApplicationCaseID { get; set; }
    
        public virtual ApplicationBloodType ApplicationBloodType { get; set; }
        public virtual ApplicationCase ApplicationCase { get; set; }
        public virtual ApplicationDistrict ApplicationDistrict { get; set; }
        public virtual ApplicationEducation ApplicationEducation { get; set; }
        public virtual ApplicationGender ApplicationGender { get; set; }
        public virtual ApplicationOrganisation ApplicationOrganisation { get; set; }
        public virtual ApplicationProvince ApplicationProvince { get; set; }
        public virtual ApplicationStaff ApplicationStaff { get; set; }
    }
}
