//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSenAdmin.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInformation
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public string SystemEmail { get; set; }
        public string SystemEmailPassword { get; set; }
        public string SystemLogo { get; set; }
        public string SystemIcon { get; set; }
        public string FacebookLink { get; set; }
        public string InstagramLink { get; set; }
        public string TwitterLink { get; set; }
        public string YoutubeLink { get; set; }
        public string WhatsAppApi { get; set; }
        public string SystemTelephone { get; set; }
        public string SystemAdress { get; set; }
        public string SystemMapsLink { get; set; }
        public string Meta { get; set; }
    }
}
