//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confederation
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public string PrezName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
