//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileGallery
    {
        public int Id { get; set; }
        public Nullable<int> BrodcastID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Broadcast Broadcast { get; set; }
        public virtual File File { get; set; }
    }
}
