//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string MemberName { get; set; }
        public string MemberSurname { get; set; }
        public string MemberPhoneNumber { get; set; }
        public string MemberInstagram { get; set; }
        public string MemberFacebook { get; set; }
        public string MemberTwitter { get; set; }
        public string MemberYoutube { get; set; }
        public string MemberEmail { get; set; }
        public string MemberTCNo { get; set; }
        public string MemberPosition { get; set; }
        public string MemberPhoto { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public bool CentralDirectors { get; set; }
        public bool CentralCheckers { get; set; }
        public bool CentralDiscipline { get; set; }
        public bool Funders { get; set; }
    }
}
