//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationBloodType> ApplicationBloodTypes { get; set; }
        public virtual DbSet<ApplicationCase> ApplicationCases { get; set; }
        public virtual DbSet<ApplicationDistrict> ApplicationDistricts { get; set; }
        public virtual DbSet<ApplicationEducation> ApplicationEducations { get; set; }
        public virtual DbSet<ApplicationGender> ApplicationGenders { get; set; }
        public virtual DbSet<ApplicationOrganisation> ApplicationOrganisations { get; set; }
        public virtual DbSet<ApplicationProvince> ApplicationProvinces { get; set; }
        public virtual DbSet<ApplicationStaff> ApplicationStaffs { get; set; }
        public virtual DbSet<BranchMember> BranchMembers { get; set; }
        public virtual DbSet<Branch> Branchs { get; set; }
        public virtual DbSet<Broadcast> Broadcasts { get; set; }
        public virtual DbSet<BrodcastClass> BrodcastClasses { get; set; }
        public virtual DbSet<Confederation> Confederations { get; set; }
        public virtual DbSet<Dropdown> Dropdowns { get; set; }
        public virtual DbSet<FileGallery> FileGalleries { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<GalleryType> GalleryTypes { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<MediaUrl> MediaUrls { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<SubBranch> SubBranches { get; set; }
        public virtual DbSet<SystemInformation> SystemInformations { get; set; }
        public virtual DbSet<SystemMedia> SystemMedias { get; set; }
        public virtual DbSet<UserClass> UserClasses { get; set; }
        public virtual DbSet<UserPage> UserPages { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VisitLog> VisitLogs { get; set; }
    }
}
