//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Union
    {
        public int Id { get; set; }
        public string UnionName { get; set; }
        public string UnionPrez { get; set; }
        public string UnionPrezPhone { get; set; }
        public string UnionPrezEmail { get; set; }
        public string UnionPrezFacebook { get; set; }
        public string UnionPrezInstagram { get; set; }
        public string UnionPrezLinkedin { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
