//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPage
    {
        public int Id { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public string CotrollerName { get; set; }
        public string ActionName { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string UrlParameter { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> Link { get; set; }
    
        public virtual UserPermission UserPermission { get; set; }
    }
}
