//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurriyetciYerelSen.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserProfilePic { get; set; }
        public Nullable<int> UserClassID { get; set; }
        public Nullable<bool> Theme { get; set; }
        public Nullable<int> ResetCode { get; set; }
        public string RememberCookie { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual UserClass UserClass { get; set; }
    }
}
